### PR TITLE
update build command `make exec` to `make`

### PR DESCRIPTION
**Pull request by emizzle**

### CODE REVIEW

**Comment by emizzle** [comment]
Anyway to test this change?

**Comment by jakubgs** [comment]
Indeed, the builds are failing:
```
admin@metal-01.he-eu-hel1.codex.test:~ % j -o cat -n 7 -u build-nim-codex-01
 >>> Building binaries...
Creating nimbus-build-system.paths
make: *** No rule to make target 'exec'.  Stop.
build-nim-codex-01.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
build-nim-codex-01.service: Failed with result 'exit-code'.
Failed to start Build nim-codex-01.
build-nim-codex-01.service: Consumed 6.817s CPU time.
```

**Comment by jakubgs** [comment]
I changed it manually for one build and it does indeed work:
```
admin@metal-01.he-eu-hel1.codex.test:~ % j -o cat -n200 -u build-nim-codex-01 | head
ls: cannot access 'build/nim_codex_de3d97db': No such file or directory
 >>> Building binaries...
Creating nimbus-build-system.paths
Building: install/usr/lib/libbacktracenim.a
Building: build/all
[NimScript] exec: nim c --out:build/codex -d:chronicles_runtime_filtering -d:chronicles_log_level=TRACE --verbosity:0 --hints:off -d:release ./codex.nim
Building Leopard-RS: cd /data/nim-codex-01/repo/nimcache/release/codex/vendor_leopard && cmake /data/nim-codex-01/repo/vendor/nim-leopard/vendor/leopard -DCMAKE_BUILD_TYPE=Release && make libleopard
-- The C compiler identification is GNU 11.2.0
-- The CXX compiler identification is GNU 11.2.0
-- Detecting C compiler ABI info
```

**Review by jakubgs — APPROVED** [review]
Thanks.

**Comment by jakubgs** [comment]
Deployed. Though the code is buggy and fails at startup:
```
Error: unhandled exception: /data/nim-codex-02/repo/vendor/nimbus-build-system/vendor/Nim/lib/pure/options.nim(133, 5) `not val.isNil`  [AssertionDefect]
```
Full log: https://gist.github.com/jakubgs/14f2bb6fb40ce5a0bc6b67a83463e9d2

**Pull request merged**
